### ISSUE TITLE
Conflict with VCA mod 

### ISSUE THREAD

**Issue by Cris5791** [loki79uk/FS22_CabView#1]
Using this mod and setting the options look right / left / forward / back of the VCA mod, when returning to the front view the position is shifted.  Thank you.

**Comment by loki79uk** [comment]
Hi - thanks for letting me know!

I've had a quick look at this, and I think it is because both CabView and VCA override the default camera resetting behaviour (see below).  I'll confirm this evening and see what I can do to prevent it.

From CabView:
```	
	-- RESET VIEW IF REQUIRED
	spec = self.vehicle.spec_cabView
	if self.isInside and spec.resetView then
		self.rotX = spec.originalRotX
		self.rotY = spec.originalRotY
		self.rotZ = spec.originalRotZ
		spec.resetView = false
	end
```
	
From VCA:
```
	if (oldCam.resetCameraOnVehicleSwitch == nil and g_gameSettings:getValue("resetCamera")) or oldCam.resetCameraOnVehicleSwitch then
	-- camera is automatically reset
	elseif ( not oldCam.isInside and self.spec_vca.camRotOutside > 0 )
			or (     oldCam.isInside and self.spec_vca.camRotInside  > 0 ) then 
		oldCam.rotY = self.spec_vca.zeroCamRotY + oldCam.rotY - self.spec_vca.lastCamRotY
	end
```

**Comment by loki79uk** [comment]
Just an update - I have not forgotten about this, but it is not straightforward to edit from my end.  I could disable the camera reset completely when VCA is installed, but it would be much easier to reset the camera using `spec.originalRotX`, etc in VCA instead of subtracting the previous settings.
