### ISSUE TITLE
Mod conflict with the realismAddon_gearbox mod from author modelleicher and the default base game keybind for clutch (Left Shift)

### ISSUE THREAD

**Issue by CaptainGuppy** [loki79uk/FS22_CabView#12]
Hi @loki79uk!
After many hours of trial and error I have discovered that the default key bind for this beautiful mod is in conflict with the [realismAddon_gearbox mod](https://github.com/modelleicher/FS22_realismAddon_gearbox) from author modelleicher and the default base game keybind for clutch (Left Shift), in the end renders the aforementioned mod unusable as there is no way for it to capture the clutch, as it is designed right now.

I've confirmed the gearbox mod works again by clearing the Left Shift key binding for "Cabin View Lean Forward" in my inputBinding.xml, altering the modDesc.xml to the below (lctrl instead of lshift) and then fire up the game - I can press the clutch and play with the gearbox mod successfully:
```
	<inputBinding>
		<actionBinding action="CABVIEW_LEAN_FORWARD" >
			<binding device="KB_MOUSE_DEFAULT" input="KEY_lctrl" />
		</actionBinding>
		
```
Would it be possible for you to update your modDesc.xml to use Left Control instead as the default key bind for Lean Forwads to avoid this issue in the future?

Thanks and best regards,
CaptainGuppy

**Comment by CaptainGuppy** [comment]
I just discovered that it's also possible to clear or change the default clutch key bind (Left Shift) which makes the mods' key bindings to not conflict, as a workaround.

**Comment by loki79uk** [comment]
Are you not able to just change the keyboard bindings in the main settings menu?

![image](https://github.com/user-attachments/assets/9c29ef8a-f0b0-4be3-b268-3e5af9c167ab)

**Comment by CaptainGuppy** [comment]
@loki79uk 
Yeah, I don't know if you saw my second message above, but yeah I discovered it a few seconds after posting - however, for me to narrow down 190+ mods to come to this took a long time, and I thought to myself: perhaps having the Realistic Cabin View keybind to not default to Left Shift would save so much time for others.

All the best,
CaptainGuppy

**Comment by loki79uk** [comment]
The trouble with FS key bindings in general is that there are barely any unused keys in the base game, let alone with mods, and any key that I choose will conflict with something.  If I don't set a default, then everyone has to set it manually, so I just set the keys that I use personally, and make it possible to change them in the menu.  Cab view keys were chosen in FS19 before the clutch was even a thing.  Left shift is just a comfortable position next to WSAD where I have my left hand most of the time anyway.

To save time if you know a key is conflicting, you can set it again in the menu and it will tell you the other actions that are conflicting (see message in the bottom right corner):

![image](https://github.com/user-attachments/assets/6fa3628d-b43b-4ccb-a884-2a5123d18617)

**Comment by CaptainGuppy** [comment]
@loki79uk 
Ah I see the problem here. Another approach could also be to **not** set a key bind and have the users set it themselves. 

The problem for me was that there was no clear indication in the realismAddon_gearbox mod that it somehow uses the "out of the box" clutch key assignment from base game and that changing the key bind from Realistic Cabin View solved it. 

This is what took sooooooo long to troubleshoot. 

I've examined my inputBinding.xml and it seems the left control is used the least, could be worth considering. 

But thanks for your time, it was worth a shot. 

All the best,
CaptainGuppy.
