### ISSUE TITLE
Is it possible to add zoom like in Inside Camera Zoom?

### ISSUE THREAD

**Issue by vitalii2011** [loki79uk/FS22_CabView#9]
https://forbidden-mods.de/filebase/file/26232-ls22-inside-camera-zoom/ 
- Inside Camera Zoom conflicts with some mods, for example Fov Control. https://github.com/VertexFloat/fovControl

**Comment by vitalii2011** [comment]
P. S.
I found another solution. Sorry to bother you. )

**Comment by loki79uk** [comment]
I was planning to look at the weekend.  What was your solution?  I can certainly add an override to leave the FOV alone when certain mods are detected.

**Comment by vitalii2011** [comment]
The Dashboard Live mod has the "Quick Zoom" option and this issue is resolved with it.
